### ISSUE TITLE
How to work for library?

### ISSUE THREAD

**Issue by standus** [composer/installers#350]
Hey,
I have this config:
```
"config": {
        "preferred-install": "dist",
		"prepend-autoloader": false,
		"vendor-dir": "bin",
		"project-root": "bin"
    },
"extra": {
        "branch-alias": {
            "dev-master": "6.2-dev"
        },
        "installer-types": ["library"],
		"installer-paths": {
			"bin/GuzzleHttp": ["guzzlehttp/guzzle"]
		}
    },
```
but it is ignored and guzzlehttp/guzzle is still installed in: bin/guzzlehttp/guzzle/src !
What am I dooing bad?

**Comment by sbuzonas** [comment]
This project does not support the `library` package type.

**Comment by landsman** [comment]
why?

**Comment by sbuzonas** [comment]
The `library` type is the default type for all packages that are not specified.

**Comment by landsman** [comment]
wtf, your last answer saying something another, or?

**Comment by sbuzonas** [comment]
Composer implicitly sets they type to `library` when it is not defined. If `composer/installers` supported the `library` type, it would hijack majority of the packages in packagist. If you need to support `library` your most likely approach would be a custom installer via plugin because each use case for library is often specific to the project.
