### ISSUE TITLE
Installers v2.0.0 ignoring installer-paths

### ISSUE THREAD

**Issue by fskwiniarek** [composer/installers#493]
After upgrading our composer/installers from 1.11.0 to 2.0.0, composer started to ignore installer-paths defined in "extra" section:
```
"extra": {
    "installer-paths": {
      "our/custom/path/{$name}/": [
        "type:some-custom-type"
      ]
    }
  }
```

**Comment by Seldaek** [comment]
I can't reproduce this, it seems to work for me with for example:

```
{
    "require": {
        "islandora/jsonld": "*",
        "composer/installers": "^2"
    },
    "extra": {
      "installer-paths": {
        "our/custom/path/{$name}/": [
          "type:drupal-module"
        ]
      }
    }
}
```

I then get the package installed in `./our/custom/path/jsonld`.

**Comment by fskwiniarek** [comment]
Thanks @Seldaek for the reply. This is the exact composer.json I'm using:
```
{
  "repositories": {
    "0": {
      ... my satis repository config ...
    },
    "packagist": false
  },
  "require": {
    "composer/installers": "^2",
    "propel/sf-propel-o-r-m-plugin": "1.4"
  },
  "extra": {
    "installer-paths": {
      "portal/plugins/{$name}/": [
        "type:symfony1-plugin"
      ]
    }
  }
}
```
Unfortunately all the packages are installed in vendor dir, including the plugin, but when I use:
`"composer/installers": "^1"`
then the plugin is properly moved into `portal/plugins/...` dir. Maybe the problem occurs only when Satis is used?

**Comment by Seldaek** [comment]
Oh I see. Now I get it. composer/installer 2.x removed support for symfony1-plugin as it is so old.. so that's why it just ends up vendor dir.

The problem really is https://github.com/propelorm/sfPropelORMPlugin/blob/master/composer.json#L8 requiring any version of composer/installers instead of pinning it to `^1`.

So the solution as you already found out is for your project to pin composer/installers to 1.x, as long as you rely on symfony1 plugins.
